// <auto-generated />
using System;
using LibraryManagement.DataAccessLibrary.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(LibraryManagementContext))]
    [Migration("20260515100107_ListToTables")]
    partial class ListToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookId")
                        .HasName("PK_Book");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookCategory", b =>
                {
                    b.Property<int>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookCategoryId"));

                    b.Property<string>("BookCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookCategoryId")
                        .HasName("PK_Book_Category");

                    b.HasIndex("BookCategoryName")
                        .IsUnique();

                    b.ToTable("BookCategory");

                    b.HasData(
                        new
                        {
                            BookCategoryId = 1,
                            BookCategoryName = "Science"
                        },
                        new
                        {
                            BookCategoryId = 2,
                            BookCategoryName = "Fiction"
                        },
                        new
                        {
                            BookCategoryId = 3,
                            BookCategoryName = "Non Fiction"
                        },
                        new
                        {
                            BookCategoryId = 4,
                            BookCategoryName = "Horror"
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookCopy", b =>
                {
                    b.Property<int>("BookCopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookCopyId"));

                    b.Property<int>("BookISBNId")
                        .HasColumnType("integer");

                    b.Property<int>("BookStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookCopyId")
                        .HasName("PK_Book_Copy");

                    b.HasIndex("BookISBNId");

                    b.HasIndex("BookStatusId");

                    b.HasIndex("CopyNumber")
                        .IsUnique();

                    b.ToTable("BookCopy");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookISBN", b =>
                {
                    b.Property<int>("BookISBNId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookISBNId"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("Edition")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.HasKey("BookISBNId")
                        .HasName("PK_Book_ISBN");

                    b.HasIndex("BookId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("BookISBN");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookStatus", b =>
                {
                    b.Property<int>("BookStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookStatusId"));

                    b.Property<string>("BookStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookStatusId")
                        .HasName("PK_Book_Status");

                    b.HasIndex("BookStatusName")
                        .IsUnique();

                    b.ToTable("BookStatus");

                    b.HasData(
                        new
                        {
                            BookStatusId = 1,
                            BookStatusName = "Available"
                        },
                        new
                        {
                            BookStatusId = 2,
                            BookStatusName = "Unavailable"
                        },
                        new
                        {
                            BookStatusId = 3,
                            BookStatusName = "Lost"
                        },
                        new
                        {
                            BookStatusId = 4,
                            BookStatusName = "Damaged"
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Borrowing", b =>
                {
                    b.Property<int>("BorrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BorrowingId"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BorrowedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("BorrowingStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BorrowingId")
                        .HasName("PK_Borrowing");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("BorrowingStatusId");

                    b.HasIndex("MemberId");

                    b.ToTable("Borrowing");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BorrowingStatus", b =>
                {
                    b.Property<int>("BorrowingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BorrowingStatusId"));

                    b.Property<string>("BorrowingStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BorrowingStatusId")
                        .HasName("PK_Borrowing_Status");

                    b.HasIndex("BorrowingStatusName")
                        .IsUnique();

                    b.ToTable("BorrowingStatus");

                    b.HasData(
                        new
                        {
                            BorrowingStatusId = 1,
                            BorrowingStatusName = "Borrowed"
                        },
                        new
                        {
                            BorrowingStatusId = 2,
                            BorrowingStatusName = "Returned"
                        },
                        new
                        {
                            BorrowingStatusId = 3,
                            BorrowingStatusName = "OverDue"
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.DamagedBook", b =>
                {
                    b.Property<int>("DamagedBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DamagedBookId"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer");

                    b.Property<int>("DamagedLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DamagedBookId")
                        .HasName("PK_Damaged_Book");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("DamagedLevelId");

                    b.HasIndex("MemberId");

                    b.ToTable("DamagedBook");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.DamagedLevel", b =>
                {
                    b.Property<int>("DamagedLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DamagedLevelId"));

                    b.Property<string>("DamagedLevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("DamagedLevelId")
                        .HasName("PK_Damaged_Level");

                    b.HasIndex("DamagedLevelName")
                        .IsUnique();

                    b.ToTable("DamagedLevel");

                    b.HasData(
                        new
                        {
                            DamagedLevelId = 1,
                            DamagedLevelName = "Little",
                            FineAmount = 100m
                        },
                        new
                        {
                            DamagedLevelId = 2,
                            DamagedLevelName = "Medium",
                            FineAmount = 300m
                        },
                        new
                        {
                            DamagedLevelId = 3,
                            DamagedLevelName = "Hard",
                            FineAmount = 500m
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FineId"));

                    b.Property<int>("BorrowingId")
                        .HasColumnType("integer");

                    b.Property<int?>("DamagedBookId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("FineCategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaidFully")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("FineId")
                        .HasName("PK_Fine");

                    b.HasIndex("BorrowingId");

                    b.HasIndex("DamagedBookId")
                        .IsUnique();

                    b.HasIndex("FineCategoryId");

                    b.ToTable("Fine");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.FineCategory", b =>
                {
                    b.Property<int>("FineCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FineCategoryId"));

                    b.Property<string>("FineCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FineCategoryId")
                        .HasName("PK_Fine_Category");

                    b.HasIndex("FineCategoryName")
                        .IsUnique();

                    b.ToTable("FineCategory");

                    b.HasData(
                        new
                        {
                            FineCategoryId = 1,
                            FineCategoryName = "Lost"
                        },
                        new
                        {
                            FineCategoryId = 2,
                            FineCategoryName = "Damaged"
                        },
                        new
                        {
                            FineCategoryId = 3,
                            FineCategoryName = "OverDue"
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MemberTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MemberId")
                        .HasName("PK_Member");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberTypeId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.MemberType", b =>
                {
                    b.Property<int>("MemberTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberTypeId"));

                    b.Property<int>("LimitDays")
                        .HasColumnType("integer");

                    b.Property<string>("MemberTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfBooks")
                        .HasColumnType("integer");

                    b.HasKey("MemberTypeId")
                        .HasName("PK_Member_Type_Id");

                    b.ToTable("MemberTypes");

                    b.HasData(
                        new
                        {
                            MemberTypeId = 1,
                            LimitDays = 7,
                            MemberTypeName = "Basic",
                            NumberOfBooks = 2
                        },
                        new
                        {
                            MemberTypeId = 2,
                            LimitDays = 10,
                            MemberTypeName = "Student",
                            NumberOfBooks = 3
                        },
                        new
                        {
                            MemberTypeId = 3,
                            LimitDays = 15,
                            MemberTypeName = "Premium",
                            NumberOfBooks = 5
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.ModeOfPayment", b =>
                {
                    b.Property<int>("ModeOfPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModeOfPaymentId"));

                    b.Property<string>("ModeOfPaymentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModeOfPaymentId")
                        .HasName("PK_Mode_Of_Payment");

                    b.HasIndex("ModeOfPaymentName")
                        .IsUnique();

                    b.ToTable("ModeOfPayment");

                    b.HasData(
                        new
                        {
                            ModeOfPaymentId = 1,
                            ModeOfPaymentName = "Cash"
                        },
                        new
                        {
                            ModeOfPaymentId = 2,
                            ModeOfPaymentName = "UPI"
                        },
                        new
                        {
                            ModeOfPaymentId = 3,
                            ModeOfPaymentName = "Credit_Card"
                        },
                        new
                        {
                            ModeOfPaymentId = 4,
                            ModeOfPaymentName = "Debit_Card"
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<int>("FineId")
                        .HasColumnType("integer");

                    b.Property<int>("ModeOfPaymentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PaymentId")
                        .HasName("PK_Payment");

                    b.HasIndex("FineId");

                    b.HasIndex("ModeOfPaymentId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId")
                        .HasName("PK_Role_Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Book", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.BookCategory", "BookCategory")
                        .WithMany("Books")
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Book_Category");

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookCopy", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.BookISBN", "BookISBN")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookISBNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Book_Copy");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.BookStatus", "BookStatus")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Book_Status");

                    b.Navigation("BookISBN");

                    b.Navigation("BookStatus");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookISBN", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.Book", "Book")
                        .WithMany("BookISBNs")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Book_ISBN");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Borrowing", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Borrowing_Book_Copy");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.BorrowingStatus", "BorrowingStatus")
                        .WithMany("Borrowings")
                        .HasForeignKey("BorrowingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Borrowing_Status");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Borrowing_Member");

                    b.Navigation("BookCopy");

                    b.Navigation("BorrowingStatus");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.DamagedBook", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("DamagedBooks")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Damaged_Book_Copy");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.DamagedLevel", "DamagedLevel")
                        .WithMany("DamagedBooks")
                        .HasForeignKey("DamagedLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Damaged_Book_Level");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.Member", "Member")
                        .WithMany("DamagedBooks")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Damaged_Book_Member");

                    b.Navigation("BookCopy");

                    b.Navigation("DamagedLevel");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Fine", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.Borrowing", "Borrowing")
                        .WithMany("Fines")
                        .HasForeignKey("BorrowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fine_Borrowing");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.DamagedBook", "DamagedBook")
                        .WithOne("Fines")
                        .HasForeignKey("LibraryManagement.ModelLibrary.Models.Fine", "DamagedBookId")
                        .HasConstraintName("FK_Fine_Damaged_Book");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.FineCategory", "FineCategory")
                        .WithMany("Fines")
                        .HasForeignKey("FineCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fine_Category");

                    b.Navigation("Borrowing");

                    b.Navigation("DamagedBook");

                    b.Navigation("FineCategory");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Member", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.MemberType", "MemberType")
                        .WithMany("Members")
                        .HasForeignKey("MemberTypeId")
                        .HasConstraintName("FK_Member_Type");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Member_Role");

                    b.Navigation("MemberType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Payment", b =>
                {
                    b.HasOne("LibraryManagement.ModelLibrary.Models.Fine", "Fine")
                        .WithMany("Payments")
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Fine");

                    b.HasOne("LibraryManagement.ModelLibrary.Models.ModeOfPayment", "ModeOfPayment")
                        .WithMany("Payments")
                        .HasForeignKey("ModeOfPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Mode");

                    b.Navigation("Fine");

                    b.Navigation("ModeOfPayment");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Book", b =>
                {
                    b.Navigation("BookISBNs");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookCopy", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("DamagedBooks");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookISBN", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BookStatus", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Borrowing", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.BorrowingStatus", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.DamagedBook", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.DamagedLevel", b =>
                {
                    b.Navigation("DamagedBooks");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Fine", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.FineCategory", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Member", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("DamagedBooks");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.MemberType", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.ModeOfPayment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LibraryManagement.ModelLibrary.Models.Role", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
